version: '3'
services:
  site:
    image: ghost:1-alpine
    ports: 
      - 2368:2368
    environment:
      database_client: mysql
      database_connection_host: db
      database__connection__user: root
      database__connection__password: root
      database__connection__database: ghost
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root